### ISSUE TITLE
No carga formulario configuración

### ISSUE THREAD

**Issue by Borty97** [uvejota/homeassistant-edata#185]
Tras hacer la instalación correcta mediante HACS no puedo seguir con la configuración.
![image](https://github.com/uvejota/homeassistant-edata/assets/60492018/e7477b9a-cfa9-4ae0-be43-e826a6d8df5c)
El asistente no avanza

**Comment by jcs86** [comment]
Me pasa exactamente lo mismo, con la versión anterior me daba error 500, con la última actualización borre la integración porque no cargaba, la volví a instalar y nada, no deja configurar. Me da este error que no sé solventar:

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 11:24:28 (3 occurrences)
Last logged: 11:25:25

Unable to install package e-data==1.1.2: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [57 lines of output] Traceback (most recent call last): File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup self).run_setup(setup_script=setup_script) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup exec(code, locals()) File "<string>", line 18, in <module> File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 140, in <module> from . import core File "/tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.11 from "/usr/local/bin/python3" * The NumPy version is: "1.23.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-_8graycs/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install package e-data==1.1.2: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [57 lines of output] Traceback (most recent call last): File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup self).run_setup(setup_script=setup_script) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup exec(code, locals()) File "<string>", line 18, in <module> File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 140, in <module> from . import core File "/tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.11 from "/usr/local/bin/python3" * The NumPy version is: "1.23.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-tn29jlc5/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install package e-data==1.1.2: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [57 lines of output] Traceback (most recent call last): File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup self).run_setup(setup_script=setup_script) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup exec(code, locals()) File "<string>", line 18, in <module> File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 140, in <module> from . import core File "/tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.11 from "/usr/local/bin/python3" * The NumPy version is: "1.23.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-dzvrf77_/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by duca2** [comment]
Si. Así estamos muchos!! A ver qué nos dicen

**Comment by jjvelar** [comment]
+1

**Comment by uvejota** [comment]
2023.06.2 liberada, no tengo demasiada fe, pero a mi me ha funcionado en HA 2023.06.0

Ya me decís...

**Comment by poleax01** [comment]
Me ha funcionado, gracias.

**Comment by duca2** [comment]
Genial!! Mil gracias 😊

**Comment by Ie0nard0** [comment]
En 2023.06.1 a mi me da el mismo error que daba la versión de ayer
